# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('artist', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('track', models.PositiveIntegerField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=15)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_db.Album')),
            ],
        ),
    ]
